apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pythonapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: bzass/basicpython:latest
        ports:
        - containerPort: 5000      